package com.kits.timetable.service;

import com.kits.timetable.dto.TimetableResponse;
import com.kits.timetable.entity.*;
import com.kits.timetable.repository.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.stream.Collectors;

@Service
public class TimetableGeneratorService {

    @Autowired private TimetableRepository timetableRepository;
    @Autowired private TimeSlotRepository timeSlotRepository;
    @Autowired private WorkloadRepository workloadRepository;
    @Autowired private RoomRepository roomRepository;

    private final List<String> MAIN_DAYS = Arrays.asList("MON", "TUE", "WED", "THU", "FRI");
    private final List<String> WEEKEND = Arrays.asList("SAT");

    public TimetableResponse generateTimetable(String dept, int sem, boolean force) {
        return null; 
    }

    @Transactional
    public void generateTheoryTimetable(String dept, int sem) {
        
        timetableRepository.clearAutoGeneratedEntries(dept, sem);
        
        List<String> sections = Arrays.asList("A", "B");
        Room defaultRoom = roomRepository.findAll().get(0);

        for (String currentSection : sections) {
            List<TimetableEntry> existingGrid = timetableRepository.findByDepartmentAndSemesterAndSection(dept, sem, currentSection);
            
            List<Workload> theoryWorkloads = workloadRepository.findByDepartmentAndSemesterAndSection(dept, sem, currentSection)
                    .stream()
                    .filter(w -> w.getSubject().getSubjectType().equals("THEORY"))
                    .collect(Collectors.toList());

            for (Workload workload : theoryWorkloads) {
                Subject subject = workload.getSubject();
                Teacher teacher = workload.getTeacher();
                
                int requiredLectures = subject.getWeeklyLectureCount();
                
                long initialScheduledCount = existingGrid.stream()
                        .filter(e -> e.getSubject().getId().equals(subject.getId()))
                        .count();
                int currentlyScheduled = (int) initialScheduledCount;

                // Pass 1: Max 1 class per day
                while (currentlyScheduled < requiredLectures) {
                    boolean placed = attemptToPlaceSubject(subject, teacher, dept, sem, currentSection, defaultRoom, existingGrid, MAIN_DAYS, 1);
                    if (!placed) {
                        placed = attemptToPlaceSubject(subject, teacher, dept, sem, currentSection, defaultRoom, existingGrid, WEEKEND, 1);
                    }

                    if (placed) {
                        currentlyScheduled++;
                    } else {
                        break; 
                    }
                }

                // Pass 2: Max 2 classes per day
                while (currentlyScheduled < requiredLectures) {
                    boolean placed = attemptToPlaceSubject(subject, teacher, dept, sem, currentSection, defaultRoom, existingGrid, MAIN_DAYS, 2);
                    if (!placed) {
                        placed = attemptToPlaceSubject(subject, teacher, dept, sem, currentSection, defaultRoom, existingGrid, WEEKEND, 2);
                    }

                    if (placed) {
                        currentlyScheduled++;
                    } else {
                        break; 
                    }
                }
            }
        }
    }

    private boolean attemptToPlaceSubject(Subject subject, Teacher teacher, String dept, int sem, String section, 
                                          Room room, List<TimetableEntry> grid, List<String> daysToTry, int maxPerDayForSection) {
        
        // 🔥 THE 100% ACCURACY FIX 🔥
        // No more randomness. Sort the days by how empty they are for this section.
        // It actively hunts for "voids" and fills them first.
        List<String> smartDays = new ArrayList<>(daysToTry);
        smartDays.sort(Comparator.comparingLong(day -> 
            grid.stream().filter(e -> e.getDay().equals(day)).count()
        ));

        long totalScheduledThisWeek = grid.stream()
                .filter(e -> e.getSubject().getId().equals(subject.getId()))
                .count();

        List<Integer> allSlotsToTry = new ArrayList<>();

        // Strict alternation between Morning and Afternoon preferences
        if (totalScheduledThisWeek % 2 == 0) {
            allSlotsToTry.addAll(Arrays.asList(1, 2, 3, 5, 6)); // Morning priority
        } else {
            allSlotsToTry.addAll(Arrays.asList(5, 6, 1, 2, 3)); // Afternoon priority
        }

        for (String day : smartDays) {
            
            // Check Section/Subject Limit (Max 1 or 2 per day)
            long countTodayForSection = grid.stream()
                    .filter(e -> e.getDay().equals(day) && e.getSubject().getId().equals(subject.getId()))
                    .count();

            if (countTodayForSection >= maxPerDayForSection) continue; 

            // Check Global Teacher Limit (Max 3 across all sections)
            long teacherDailyLoad = timetableRepository.countByTeacherAndDay(teacher, day);
            if (teacherDailyLoad >= 3) continue;

            for (Integer slotOrder : allSlotsToTry) {
                boolean isSectionBusy = grid.stream().anyMatch(e -> e.getDay().equals(day) && e.getTimeSlot().getSlotOrder() == slotOrder);
                boolean isTeacherBusy = timetableRepository.existsByTeacherAndDayAndTimeSlot_SlotOrder(teacher, day, slotOrder);

                if (!isSectionBusy && !isTeacherBusy) {
                    TimeSlot slotToAssign = timeSlotRepository.findAll().stream()
                            .filter(ts -> ts.getSlotOrder() == slotOrder).findFirst().get();

                    TimetableEntry newEntry = new TimetableEntry();
                    newEntry.setDay(day);
                    newEntry.setDepartment(dept);
                    newEntry.setSemester(sem);
                    newEntry.setSection(section);
                    newEntry.setBatch("ALL");
                    newEntry.setIsManual(false); 
                    newEntry.setTimeSlot(slotToAssign);
                    newEntry.setSubject(subject);
                    newEntry.setTeacher(teacher);
                    newEntry.setRoom(room);

                    timetableRepository.saveAndFlush(newEntry);
                    grid.add(newEntry); 
                    
                    return true; 
                }
            }
        }
        return false; 
    }
}



















// package com.kits.timetable.service;

// import com.kits.timetable.dto.TimetableResponse;
// import com.kits.timetable.entity.*;
// import com.kits.timetable.repository.*;
// import org.springframework.beans.factory.annotation.Autowired;
// import org.springframework.stereotype.Service;
// import org.springframework.transaction.annotation.Transactional;

// import java.util.*;
// import java.util.stream.Collectors;

// @Service
// public class TimetableGeneratorService {

//     @Autowired private TimetableRepository timetableRepository;
//     @Autowired private TimeSlotRepository timeSlotRepository;
//     @Autowired private WorkloadRepository workloadRepository;
//     @Autowired private RoomRepository roomRepository;

//     private final List<String> MAIN_DAYS = Arrays.asList("MON", "TUE", "WED", "THU", "FRI");
//     private final List<String> WEEKEND = Arrays.asList("SAT");

//     public TimetableResponse generateTimetable(String dept, int sem, boolean force) {
//         return null; 
//     }

//     @Transactional
//     public void generateTheoryTimetable(String dept, int sem) {
        
//         timetableRepository.clearAutoGeneratedEntries(dept, sem);
        
//         List<String> sections = Arrays.asList("A", "B");
//         Room defaultRoom = roomRepository.findAll().get(0);

//         for (String currentSection : sections) {
//             List<TimetableEntry> existingGrid = timetableRepository.findByDepartmentAndSemesterAndSection(dept, sem, currentSection);
            
//             List<Workload> theoryWorkloads = workloadRepository.findByDepartmentAndSemesterAndSection(dept, sem, currentSection)
//                     .stream()
//                     .filter(w -> w.getSubject().getSubjectType().equals("THEORY"))
//                     .collect(Collectors.toList());

//             for (Workload workload : theoryWorkloads) {
//                 Subject subject = workload.getSubject();
//                 Teacher teacher = workload.getTeacher();
                
//                 int requiredLectures = subject.getWeeklyLectureCount();
                
//                 long initialScheduledCount = existingGrid.stream()
//                         .filter(e -> e.getSubject().getId().equals(subject.getId()))
//                         .count();
//                 int currentlyScheduled = (int) initialScheduledCount;

//                 while (currentlyScheduled < requiredLectures) {
//                     boolean placed = attemptToPlaceSubject(subject, teacher, dept, sem, currentSection, defaultRoom, existingGrid, MAIN_DAYS, 1);
//                     if (!placed) {
//                         placed = attemptToPlaceSubject(subject, teacher, dept, sem, currentSection, defaultRoom, existingGrid, WEEKEND, 1);
//                     }

//                     if (placed) {
//                         currentlyScheduled++;
//                     } else {
//                         break; 
//                     }
//                 }

//                 while (currentlyScheduled < requiredLectures) {
//                     boolean placed = attemptToPlaceSubject(subject, teacher, dept, sem, currentSection, defaultRoom, existingGrid, MAIN_DAYS, 2);
//                     if (!placed) {
//                         placed = attemptToPlaceSubject(subject, teacher, dept, sem, currentSection, defaultRoom, existingGrid, WEEKEND, 2);
//                     }

//                     if (placed) {
//                         currentlyScheduled++;
//                     } else {
//                         break; 
//                     }
//                 }
//             }
//         }
//     }

//     private boolean attemptToPlaceSubject(Subject subject, Teacher teacher, String dept, int sem, String section, 
//                                           Room room, List<TimetableEntry> grid, List<String> daysToTry, int maxPerDayForSection) {
        
//         List<String> shuffledDays = new ArrayList<>(daysToTry);
//         Collections.shuffle(shuffledDays); 

//         long totalScheduledThisWeek = grid.stream()
//                 .filter(e -> e.getSubject().getId().equals(subject.getId()))
//                 .count();

//         List<Integer> allSlotsToTry = new ArrayList<>();

//         if (totalScheduledThisWeek % 2 == 0) {
//             allSlotsToTry.addAll(Arrays.asList(1, 2, 3, 5, 6));
//         } else {
//             allSlotsToTry.addAll(Arrays.asList(5, 6, 1, 2, 3));
//         }

//         for (String day : shuffledDays) {
            
//             // 1. Check Section/Subject Constraint
//             long countTodayForSection = grid.stream()
//                     .filter(e -> e.getDay().equals(day) && e.getSubject().getId().equals(subject.getId()))
//                     .count();

//             if (countTodayForSection >= maxPerDayForSection) continue; 

//             // 2. Check Global Teacher Constraint (Max 3 per day across all sections)
//             long teacherDailyLoad = timetableRepository.countByTeacherAndDay(teacher, day);
//             if (teacherDailyLoad >= 3) continue;

//             for (Integer slotOrder : allSlotsToTry) {
//                 boolean isSectionBusy = grid.stream().anyMatch(e -> e.getDay().equals(day) && e.getTimeSlot().getSlotOrder() == slotOrder);
//                 boolean isTeacherBusy = timetableRepository.existsByTeacherAndDayAndTimeSlot_SlotOrder(teacher, day, slotOrder);

//                 if (!isSectionBusy && !isTeacherBusy) {
//                     TimeSlot slotToAssign = timeSlotRepository.findAll().stream()
//                             .filter(ts -> ts.getSlotOrder() == slotOrder).findFirst().get();

//                     TimetableEntry newEntry = new TimetableEntry();
//                     newEntry.setDay(day);
//                     newEntry.setDepartment(dept);
//                     newEntry.setSemester(sem);
//                     newEntry.setSection(section);
//                     newEntry.setBatch("ALL");
//                     newEntry.setIsManual(false); 
//                     newEntry.setTimeSlot(slotToAssign);
//                     newEntry.setSubject(subject);
//                     newEntry.setTeacher(teacher);
//                     newEntry.setRoom(room);

//                     // Using saveAndFlush guarantees the next DB query accurately reflects this new class
//                     timetableRepository.saveAndFlush(newEntry);
//                     grid.add(newEntry); 
                    
//                     return true; 
//                 }
//             }
//         }
//         return false; 
//     }
// }