package com.kits.timetable.repository;

import com.kits.timetable.entity.Teacher;
import com.kits.timetable.entity.TimetableEntry;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Repository
public interface TimetableRepository extends JpaRepository<TimetableEntry, Long> {
    
    List<TimetableEntry> findByDepartmentAndSemesterAndSection(String department, int semester, String section);

    boolean existsByTeacherAndDayAndTimeSlot_SlotOrder(Teacher teacher, String day, Integer slotOrder);

    long countByTeacherAndDay(Teacher teacher, String day);

    @Modifying
    @Transactional
    @Query("DELETE FROM TimetableEntry t WHERE t.department = :dept AND t.semester = :sem AND (t.isManual IS NULL OR t.isManual = false)")
    void clearAutoGeneratedEntries(String dept, int sem);

    // Added methods for cascading deletes
    void deleteByTeacher(com.kits.timetable.entity.Teacher teacher);
    void deleteBySubject(com.kits.timetable.entity.Subject subject);
}